---
kind: pipeline
name: default

steps:
  - name: export static
    image: node:10
    commands:
      - yarn install --prod=false
      - NODE_ENV=production DEPLOY_ENV=github yarn build && touch out/.nojekyll

  - name: deploy to github page
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_user
      password:
        from_secret: github_pawd
      ssh_key:
        from_secret: github_sshkey
      pages_directory: public/
